#!/usr/bin/python3
import sys
import os

if len(sys.argv) > 1:
    option = sys.argv[1]
    sys.argv = sys.argv[:1] + sys.argv[2:]

    if option == "create_project":
        from lcc.bin.create_project import main
        main()
    else:
        import importlib.util
    try:
        spec = importlib.util.spec_from_file_location("module.name", os.path.join(os.getcwd(), 'project_settings.py'))
        project_settings = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(project_settings)
    except IOError:
        raise IOError("There are not 'project_settings.py' in the currect directory. Create project first by 'lcc create_project'")

    if option == "make_filter":
        from lcc.bin.make_filter import main
        main(project_settings)

    elif option == "filter_stars":
        from lcc.bin.filter_stars import main
        main(project_settings)

    elif option == "prepare_query":
        from lcc.bin.prepare_query import main
        main(project_settings)
    else:
        sys.stderr.write("\nInvalid option. Parameter of lcc have to be 'make_filter', 'filter_stars' or 'prepare_query'\n")