function decodeGetPars(a){var b={};a=a.slice(1).split("&");for(var d in a){var c=a[d].split("="),e="arg"+unescape(c[0]).replace("+"," "),c=unescape(c[1]).replace("+"," ");void 0==b[e]&&(b[e]=[]);b[e].push(c)}return b}function isIn(a,b){for(var d in b)if(b[d]==a)return!0;return!1}function getJD(a){return a/864E5+2440587.5}function getJYear(a){return(getJD(a)-2451545)/365.25+2E3}
function htmlEscape(a){return String(a).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&apos;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
(function(){var a={};this.renderTemplate=function(b,d){var c=a[b];c||(str=document.getElementById(b).innerHTML,c="var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+str.replace(/[\r\t\n]/g," ").split("'").join("\\'").split("\t").join("'").replace(/\$([a-zA-Z_]+)/g,"',htmlEscape($1),'").replace(/\$!([a-zA-Z_]+)/g,"',$1,'")+"');}return $.trim(p.join(''));",c=new Function("obj",c),a[str]=c);return c(d)}})();
function getEnclosingForm(a){return"FORM"==a.nodeName?a:getEnclosingForm(a.parentNode)}function getSelectedEntries(a){var b=[],d;for(d=0;d<a.length;d++)a.options[d].selected&&b.push(a.name+"="+encodeURIComponent(a.options[d].value));return b}
function makeQueryItem(a){var b=null;switch(a.nodeName){case "INPUT":case "TEXTAREA":"radio"==a.type||"checkbox"==a.type?a.checked&&(b=a.name+"="+encodeURIComponent(a.value)):a.name&&a.value&&(b=a.name+"="+encodeURIComponent(a.value));break;case "SELECT":return getSelectedEntries(a).join("&");case "BUTTON":break;default:alert("No handler for "+a.nodeName)}return b?b:a.NodeName}
function getFormQuery(a,b){var d=[],c;items=a.elements;for(c=0;c<items.length;c++){var e=makeQueryItem(items[c]);e&&void 0==b[items[c].name]&&d.push(e)}return a.getAttribute("action")+"?"+d.join("&")}function makeResultLink(a){return getFormQuery(a,[])}function makeBookmarkLink(a){return getFormQuery(a,{__nevow_form__:1})}var expandedMetaWidth="200px";function markFold(a,b){return a.slice(0,a.length-2)+b}
function toggleCollapsedMeta(a){var b=a.parentNode.nextSibling;"visible"==b.style.visibility?(a.childNodes[0].data=markFold(a.childNodes[0].data,">>"),collapseMeta(b)):(a.childNodes[0].data=markFold(a.childNodes[0].data,"<<"),expandMeta(b))}function collapseMeta(a){a.style.visibility="hidden";a.style.height="0px";a.style.maxHeight="0px";a=a.parentNode;a.style.border="0px none #707ca0";a.style.padding="1px";a.style.background="none"}
function expandMeta(a){a.style.visibility="visible";a.style.height="auto";a.style.maxHeight="200px";a.style.width=expandedMetaWidth;a=a.parentNode;a.style.border="1px solid #707ca0";a.style.padding="3px";a.style.background="#ffffff";a.style.width=expandedMetaWidth}function followEmbeddedLink(a){for(index in a.childNodes)if(child=a.childNodes[index],child.href){window.location=child.href;break}}function output_BussedElement(a,b,d){a.id=b;for(var c in d)a["visibleFor_"+d[c]]=!0;return a}
function output_verbSelector(a){var b=["H","1","2","3"],d=document.createElement("span"),c=document.createElement("select");d["class"]="op_widget";d.appendChild(document.createTextNode(" output verbosity "));c.name="_VERB";a=void 0!=a["arg"+c.name]?a["arg"+c.name][0]:"H";for(verbInd in b){var e=c.appendChild(document.createElement("option")),f=b[verbInd];e.appendChild(document.createTextNode(f));f==a&&(e.selected="selected")}d.appendChild(c);return output_BussedElement(d,"op_verb",["VOTable","FITS",
"TSV"])}function output_tdEncSelector(a){var b=document.createElement("span"),d=document.createElement("input");b["class"]="op_widget";d.name="_TDENC";a=void 0!=a["arg"+d.name]?a["arg"+d.name][0]:"false";d.type="checkbox";d.style.width="auto";b.appendChild(d);b.appendChild(document.createTextNode(" human-readable "));"true"==a&&(d.checked="checked");return output_BussedElement(b,"op_tdenc",["VOTable"])}
function output_setFormat(a){for(var b=document.getElementById("genForm-_FORMAT").options,d=0;d<b.length;d++)b[d].selected=b[d].value==a?!0:!1}var output_bussedElements=[];
function output_init(){var a=decodeGetPars(location.search),b=a.arg_FORMAT;document.getElementById("genForm-_OUTPUT")&&(output_bussedElements.push(output_verbSelector(a)),output_bussedElements.push(output_tdEncSelector(a)),output_bussedElements.push(output_itemSelector(a)),void 0==b&&(b="HTML"),output_broadcast(b),outputInited=!0)}
function output_broadcast(a){var b="visibleFor_"+a;output_setFormat(a);for(var d in output_bussedElements)a=output_bussedElements[d],a[b]?output_show(a):output_hide(a)}$(document).ready(function(){output_init()});function makeTabCallback(a){return function(b){$("#tabset_tabs > li").removeClass("selected");b=$(b.currentTarget);b.addClass("selected");b=b.find("a").attr("name");a[b]($("#mainbox"))}}
function popupInnerWindow(a,b,d){var c=a.parent();c.css({position:"relative"});a.detach();a.css("visibility","visible");var e=$("<div class='innerWin'/>"),f=$("<p class='innerTitle'><span class='closer'>x&nbsp;</span></p>");e.append(f);e.append(a);a.addClass("innerBody");a.show();e.draggable({cancel:".innerBody"});b.append(e);e.css({width:a.width(),height:a.height()+f.height(),position:"relative"});closer=function(b){e.hide();e.detach();a.detach();a.hide();c.append(a);d()};e.find(".closer").bind("click",
closer);return closer}function output_popupAddSel(){var a=output_bussedElements[2],b=popupInnerWindow($("#genForm-_ADDITEMS"),$("#genForm-_OUTPUT"),function(){a.unbind("click");a.bind("click",output_popupAddSel);a.contents()[0].data="More output fields"});a.unbind("click");a.bind("click",b);a.contents()[0].data="Pop down field selector";return!1}
function output_itemSelector(a){a=$('<button type="button" id="op_additem" class="popButton">More output fields</button>');a.bind("click",output_popupAddSel);var b=[];document.getElementById("genForm-_ADDITEMS")&&b.push("HTML");return res=output_BussedElement(a,"op_additem",b)}function output_show(a){if(!document.getElementById(a.id)){var b=$("#genForm-_OUTPUT");b.append(document.createTextNode(" "));b.append(a)}}function output_hide(a){document.getElementById(a.id)&&$(a).detach()}DATETIME_RE=/^(\d\d\d\d)-(\d\d)-(\d\d)[T ](\d\d):(\d\d):(\d\d.?\d*)$/;
DATE_RE=/^(\d\d\d\d)-(\d\d)-(\d\d)$/;function _getValue(a){var b=DATETIME_RE.exec(a);if(null!=b)return a=new Date(parseFloat(b[1]),parseFloat(b[2]),parseFloat(b[3]),parseFloat(b[4]),parseFloat(b[5]),parseFloat(b[6])),getJYear(a);b=DATE_RE.exec(a);if(null!=b)return a=new Date(parseFloat(b[1]),parseFloat(b[2]),parseFloat(b[3])),getJYear(a);a=parseFloat(a);return a==a?a:null}
function _doLinePlot(a,b,d,c){var e=[],f={series:{}};a.find("tr.data").each(function(a,c){var f=$(c).children(),l=_getValue(f[b].firstChild.data),f=_getValue(f[d].firstChild.data);null!=l&&null!=f&&e.push([l,f])});"Lines"==c?(f.series.lines={show:!0},e.sort(function(a,b){return a[0]-b[0]})):f.series.points={show:!0};jQuery.plot(jQuery("#plotarea"),[e],f)}
function _makeHistogram(a,b){if(2>a.length)return[];a.sort(function(a,b){return a-b});var d=a[0],c=(a[a.length-1]-d)/b;0==c&&(c=1);for(var e=[],f=0;f<b;f++)e.push(0);for(index in a)e[Math.floor((a[index]-d)/c)]++;a=[];for(index in e)a.push([index*c+d,e[index]]);return a}
function _doHistogramPlot(a,b){var d=[];a.find("tr.data").each(function(a,c){var g=_getValue($(c).children()[b].firstChild.data);null!=g&&d.push(g)});var c=_makeHistogram(d,20);jQuery.plot(jQuery("#plotarea"),[{bars:{show:!0,barWidth:c[1][0]-c[0][0]},data:c}])}function _doFlotPlot(a,b,d,c){xInd=b.find("option:selected").val();yInd=d.find("option:selected").val();style=c.find("option:selected").val();"Histogram"==yInd?_doHistogramPlot(a,xInd):_doLinePlot(a,xInd,yInd,style)}
function _plotUsingFlot(a,b){var d=$('<div id="plotcontainer" style="position:fixed;z-index:3000;background:white;padding-left:3px;padding-right:3px;padding-bottom:3px;border:2px solid gray"><p class="innerTitle"><span class="closer">x&nbsp;</span></p><div id="plotarea" style="width:700px;height:400px;"/></div>');d.draggable();d.find(".closer").bind("click",function(){d.remove()});var c=$('<p class="flotControl"></p>');d.append(c);var e=$("<select/>");$(a.find("tr")[0]).find("th").each(function(a,
b){e.append($('<option value="'+a+'">'+$(b).text()+"</option>"))});c.append(e);c.append(" vs. ");var f=e.clone();f.append($('<option value="Histogram">Histogram</option>'));c.append(f);c.append(" using ");var g=$('<select><option selected="selected">Points</option><option>Lines</option></select>');c.append(g);c=0;b.xselIndex&&(c=b.xselIndex);var h=f.children().length-1;b.yselIndex&&(h=b.yselIndex);var k=0;b.usingIndex&&(k=b.usingIndex);e.children()[c].setAttribute("selected","selected");f.children()[h].setAttribute("selected",
"selected");g.children()[k].setAttribute("selected","selected");c=function(){try{_doFlotPlot(a,e,f,g)}catch(b){throw jQuery.plot(jQuery("#plotarea"),[{data:[],label:"unplottable"}]),b;}};e.change(c);f.change(c);g.change(c);$("body").prepend(d);c()}function openFlotPlot(a,b){void 0==b&&(b={});$.getScript("/static/js/jquery.flot.js",function(){_plotUsingFlot(a,b)})}
function openVOPlot(){votURL=getFormQuery(document.getElementById("genForm"),{_FORMAT:1,_TDENC:1})+"&_FORMAT=VOTable&_TDENC=on&_VERB=H";window.open("/__system__/run/voplot/fixed?source="+encodeURIComponent(votURL),"_self")}
function insertPreview(a,b){if(a.getAttribute("href")){var d=a.getAttribute("href"),c="preview=True&width="+b,e="?";-1!=d.indexOf("?")&&(e="&");a.removeAttribute("onmouseover");$(a).addClass("busy");var d=d+e+c,f=$("<img/>").attr("src",d).attr("alt","[preview image]");f.bind("load",function(){a.replaceChild(f[0],a.firstChild);$(a).removeClass("busy")});f.bind("error",function(){$(a).removeClass("busy")})}};