var samp=function(){TYPE_STRING="string";TYPE_LIST="list";TYPE_MAP="map";var x=function(k){if("string"===typeof k)return TYPE_STRING;if(k instanceof Array)return TYPE_LIST;if(k instanceof Object&&null!==k)return TYPE_MAP;throw Error("Not legal SAMP object type: "+k);},s=function(k,j){var a=k.childNodes,b,d=[],c;for(c=0;c<a.length;c++)if(b=a[c],1===b.nodeType){if(j&&b.tagName!==j)throw Error("Child <"+a[c].tagName+"> of <"+k.tagName+"> is not a <"+j+">");d.push(b)}return d},t=function(k,j){var a=s(k,
j);if(1===a.length)return a[0];throw Error("No sole child of <"+k.tagName+">");},u=function(k){var j="",a,b;for(a=0;a<k.childNodes.length;a++){b=k.childNodes[a];if(1===b.nodeType)throw Error("Element found in text content");if(3===b.nodeType||4===b.nodeType)j+=b.nodeValue}return j},i={escapeXml:function(k){return k.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},checkParams:function(k,j){var a;for(a=0;a<j.length;a++)if(j[a]!==TYPE_STRING&&j[a]!==TYPE_LIST&&j[a]!==TYPE_MAP)throw Error("Unknown type "+
j[a]+" in check list");var b=k.length,d=[],c=!0;for(a=0;a<b;a++)d.push(x(k[a]));c=c&&j.length===b;for(a=0;c&&a<b;a++)c=c&&j[a]===d[a];if(!c)throw Error("Param type list mismatch: ["+j+"] != ["+d+"]");},valueToXml:function j(a,b){var b=b||"",d,c;c=x(a);if(c===TYPE_STRING)return b+"<value><string>"+i.escapeXml(a)+"</string></value>";if(c===TYPE_LIST){c=[];c.push(b+"<value>",b+"  <array>",b+"    <data>");for(d=0;d<a.length;d++)c.push(j(a[d],b+"      "));c.push(b+"    </data>",b+"  </array>",b+"</value>");
return c.join("\n")}if(c===TYPE_MAP){c=[];c.push(b+"<value>");c.push(b+"  <struct>");for(d in a)c.push(b+"    <member>"),c.push(b+"      <name>"+i.escapeXml(d)+"</name>"),c.push(j(a[d],b+"      ")),c.push(b+"    </member>");c.push(b+"  </struct>");c.push(b+"</value>");return c.join("\n")}throw Error("bad type");},xmlToValue:function a(b,d){var c=s(b),e;if(0===c.length)return u(b);if(1===c.length){c=c[0];e=c.tagName;if("string"===e)return u(c);if("array"===e){e=s(t(c,"data"),"value");for(var h=[],
c=0;c<e.length;c++)h.push(a(e[c],d));return h}if("struct"===e){for(var h=s(c,"member"),f={},v,g,i,c=0;c<h.length;c++){g=v=void 0;for(e=0;e<h[c].childNodes.length;e++)i=h[c].childNodes[e],1==i.nodeType&&("name"===i.tagName?v=u(i):"value"===i.tagName&&(g=a(i,d)));if(void 0!==v&&void 0!==g)f[v]=g;else throw Error("No <name> and/or <value> in <member>?");}return f}if(d&&("int"===e||"i4"===e))return u(c);throw Error("Non SAMP-friendly value content: <"+e+">");}throw Error("Bad XML-RPC <value> content - multiple elements");
},decodeParams:function(a){var a=s(a,"param"),b,d=[];for(b=0;b<a.length;b++)d.push(i.xmlToValue(t(a[b],"value")));return d},decodeFault:function(a){a=i.xmlToValue(t(a,"value"),!0);return new i.Fault(a.faultString,a.faultCode)},decodeResponse:function(a){a=a.documentElement;if("methodResponse"!==a.tagName)throw Error("Response element is not <methodResponse>");a=t(a);if("fault"===a.tagName)return i.decodeFault(a);if("params"===a.tagName)return i.decodeParams(a)[0];throw Error("Bad XML-RPC response - unknown element <"+
a.tagName+">");},Fault:function(a,b){this.faultString=a;this.faultCode=b}};i.Fault.prototype.toString=function(){return"XML-RPC Fault ("+this.faultCode+"): "+this.faultString};var n=function(a,b){this.methodName=a;this.params=b||[]};n.prototype.toString=function(){return this.methodName+"("+("undefined"===typeof JSON?"...":JSON.stringify(this.params))+")"};n.prototype.addParam=function(a){this.params.push(a);return this};n.prototype.addParams=function(a){var b;for(b=0;b<a.length;b++)this.params.push(a[b]);
return this};n.prototype.checkParams=function(a){i.checkParams(this.params,a)};n.prototype.toXml=function(){var a=[];a.push("<?xml version='1.0'?>","<methodCall>","  <methodName>"+this.methodName+"</methodName>","  <params>");for(var b=0;b<this.params.length;b++)a.push("    <param>",i.valueToXml(this.params[b],"      "),"    </param>");a.push("  </params>","</methodCall>");return a.join("\n")};var q=function(a){this.endpoint=a||"http://localhost:21012/"};q.createXHR=function(){var a=function(a){this.xhr=
a;var b=this;a.onreadystatechange=function(){if(4===a.readyState&&(!b.completed&&200===+a.status)&&(b.completed=!0,b.responseText=a.responseText,b.responseXML=a.responseXML,b.onload))b.onload()};var d=this;a.onerror=function(a){d.completed||(d.completed=!0,d.onerror&&(a?a.toString=function(){return"No hub?"}:a="No hub?",d.onerror(a)))};var f=this;a.ontimeout=function(){if(!f.completed&&(f.completed=!0,f.onerror))f.onerror("timeout")}};a.prototype.open=function(a,b){this.xhr.open(a,b)};a.prototype.send=
function(a){this.xhr.send(a)};a.prototype.abort=function(){this.xhr.abort()};a.prototype.setContentType=function(a){"setRequestHeader"in this.xhr&&this.xhr.setRequestHeader("Content-Type",a)};var b=function(a){this.xdr=a;var b=this;a.onload=function(){b.responseText=a.responseText;if("text/xml"===a.contentType||"application/xml"===a.contentType||/\/x-/.test(a.contentType))try{var d=new ActiveXObject("Microsoft.XMLDOM");d.loadXML(a.responseText);b.responseXML=d}catch(h){b.responseXML=h}if(b.onload)b.onload()};
var d=this;a.onerror=function(a){if(d.onerror)d.onerror(a)};var f=this;a.ontimeout=function(a){if(f.onerror)f.onerror(a)}};b.prototype.open=function(a,b){this.xdr.open(a,b)};b.prototype.send=function(a){this.xdr.send(a)};b.prototype.abort=function(){this.xdr.abort()};b.prototype.setContentType=function(){};if("undefined"!==typeof XMLHttpRequest){var d=new XMLHttpRequest;if("withCredentials"in d)return new a(d)}if("undefined"!==typeof XDomainRequest)return new b(new XDomainRequest);if("undefined"!==
typeof flensed.flXHR)return new a(new flensed.flXHR({instancePooling:!0}));throw Error("no cross-origin mechanism available");};q.prototype.execute=function(a,b,d){var c;try{c=q.createXHR(),c.open("POST",this.endpoint),c.setContentType("text/xml")}catch(e){throw d(e),e;}c.onload=function(){var a=c.responseXML,e;if(a){try{e=i.decodeResponse(a)}catch(g){d&&d(g);return}e instanceof i.Fault?d&&d(e):b&&b(e)}else d&&d("no XML response")};c.onerror=function(a){a?a.toString=function(){return"No hub?"}:a=
"No hub";d&&d(a)};c.send(a.toXml())};var r=function(a){this.regInfo=a;this.privateKey=a["samp.private-key"];if("string"===!typeof this.privateKey)throw Error("Bad registration object");this.xClient=new q},m={call:[TYPE_STRING,TYPE_STRING,TYPE_MAP],callAll:[TYPE_STRING,TYPE_MAP],callAndWait:[TYPE_STRING,TYPE_MAP,TYPE_STRING],declareMetadata:[TYPE_MAP],declareSubscriptions:[TYPE_MAP],getMetadata:[TYPE_STRING],getRegisteredClients:[],getSubscribedClients:[TYPE_STRING],getSubscriptions:[TYPE_STRING],
notify:[TYPE_STRING,TYPE_MAP],notifyAll:[TYPE_MAP],ping:[],reply:[TYPE_STRING,TYPE_MAP]},p;for(p in m)(function(a,b){r.prototype[a]=function(d,c,e){var h=this,e=e||function(){h.close()};i.checkParams(d,b);var f=new n("samp.webhub."+a);f.addParam(this.privateKey);f.addParams(d);return this.xClient.execute(f,c,e)}})(p,m[p]);r.prototype.unregister=function(){if(this.callbackRequest)try{this.callbackRequest.abort()}catch(a){}var b=new n("samp.webhub.unregister");b.addParam(this.privateKey);try{this.xClient.execute(b)}catch(d){}delete this.regInfo;
delete this.privateKey};r.prototype.close=function(){if(!this.closed){this.closed=!0;try{this.regInfo&&this.unregister()}catch(a){}if(this.onclose){oc=this.onclose;delete this.onclose;try{oc()}catch(b){}}}};r.prototype.setCallable=function(a,b){if(this.callbackRequest)try{this.callbackRequest.abort()}catch(d){}finally{delete this.callbackRequest}if(a||this.regInfo){var c=new n("samp.webhub.allowReverseCallbacks");c.addParam(this.privateKey);c.addParam(a?"1":"0");var e,h=this;e=function(){h.close()};
if(a){var f=this,g,i=function(b){if(x(b)!=TYPE_LIST)l(Error("pullCallbacks result not List"));else{var c;for(c=0;c<b.length;c++)try{var d=b[c],e=d["samp.methodName"],h=d["samp.params"],f=void 0;"receiveNotification"===e?f=a.receiveNotification:"receiveCall"===e?f=a.receiveCall:"receiveResponse"===e&&(f=a.receiveResponse);f&&f.apply(a,h)}catch(g){}m()}},l=function(){1E3>(new Date).getTime()-g?f.close():m()},m=function(){if(f.regInfo){var a=new n("samp.webhub.pullCallbacks");a.addParam(f.privateKey);
a.addParam("600");g=(new Date).getTime();f.callbackRequest=f.xClient.execute(a,i,l)}};f.xClient.execute(c,function(){m();b()},e)}else this.xClient.execute(c,b,e)}};r.prototype.translateUrl=function(a){return(this.regInfo["samp.url-translator"]||"")+a};r.Action=function(a,b,d){this.actName=a;this.actArgs=b;this.resultKey=d};m=function(){this.callHandler={};this.replyHandler={}};m.prototype.init=function(){};m.prototype.receiveNotification=function(a,b){var d=b["samp.mtype"],c=!1;if(d in this.callHandler){try{this.callHandler[d](a,
b,!1)}catch(e){}c=!0}return c};m.prototype.receiveCall=function(a,b,d){var c=d["samp.mtype"],e=!1,h,f;if(c in this.callHandler)try{f=this.callHandler[c](a,d,!0)||{},h={"samp.status":"samp.ok","samp.result":f},e=!0}catch(g){h={"samp.status":"samp.error","samp.error":{"samp.errortxt":g.toString()}}}else h={"samp.status":"samp.warning","samp.result":{},"samp.error":{"samp.errortxt":"no action"}};this.connection.reply([b,h]);return e};m.prototype.receiveResponse=function(a,b,d){var c=!1;if(b in this.replyHandler)try{this.replyHandler[b](a,
b,d),c=!0}catch(e){}return c};m.prototype.calculateSubscriptions=function(){var a={},b;for(b in this.callHandler)a[b]={};return a};p=function(){var a=this;this.ids={};this.metas={};this.subs={};this.replyHandler={};this.callHandler={"samp.hub.event.shutdown":function(){a.connection.close()},"samp.hub.disconnect":function(){a.connection.close()},"samp.hub.event.register":function(b,d){var c=d["samp.params"].id;a.ids[c]=!0;a.changed(c,"register",null)},"samp.hub.event.unregister":function(b,d){var c=
d["samp.params"].id;delete a.ids[c];delete a.metas[c];delete a.subs[c];a.changed(c,"unregister",null)},"samp.hub.event.metadata":function(b,d){var c=d["samp.params"].id,e=d["samp.params"].metadata;a.metas[c]=e;a.changed(c,"meta",e)},"samp.hub.event.subscriptions":function(b,d){var c=d["samp.params"].id,e=d["samp.params"].subscriptions;a.subs[c]=e;a.changed(c,"subs",e)}}};var g;g=function(){};g.prototype=m.prototype;g=new g;p.prototype=g;p.prototype.changed=function(a,b,d){if(this.onchange)this.onchange(a,
b,d)};p.prototype.init=function(a){var b=this;this.connection=a;var d=function(c,d,h,f){a[h]([c],function(a){f[c]=a;b.changed(c,d,a)})};a.getRegisteredClients([],function(a){var e,h;b.ids={};for(e=0;e<a.length;e++)h=a[e],b.ids[h]=!0,d(h,"meta","getMetadata",b.metas),d(h,"subs","getSubscriptions",b.subs);b.changed(null,"ids",null)})};p.prototype.getName=function(a){var b=this.metas[a];return b&&b["samp.name"]?b["samp.name"]:"["+a+"]"};g=function(a,b,d,c){this.name=a;this.meta=b;this.callableClient=
d;this.subs=c;this.regTextNodes=[];this.whenRegs=[];this.whenUnregs=[];this.onunreg=this.onreg=this.connection=void 0};var y=function(a,b){var d,c=a.regTextNodes,e;for(d=0;d<c.length;d++)e=c[d],e.innerHTML="",e.appendChild(document.createTextNode(b))};g.prototype.setConnection=function(a){var b=this;if(this.connection&&(this.connection.close(),this.onunreg))try{this.onunreg()}catch(d){}if(this.connection=a)if(a.onclose=function(){b.connection=null;if(b.onunreg)try{b.onunreg()}catch(a){}b.update()},
this.meta&&a.declareMetadata([this.meta]),this.callableClient&&(this.callableClient.init&&this.callableClient.init(a),a.setCallable(this.callableClient,function(){a.declareSubscriptions([b.subs])})),this.onreg)try{this.onreg(a)}catch(c){}this.update()};g.prototype.register=function(){var a=this;w(this.name,function(b){a.setConnection(b);y(a,b?"Yes":"No")},function(b){y(a,"no ("+b.toString()+")")})};g.prototype.unregister=function(){this.connection&&(this.connection.unregister([]),this.setConnection(null))};
g.prototype.createRegButtons=function(){var a=this,b=document.createElement("button");b.setAttribute("type","button");b.appendChild(document.createTextNode("Register"));b.onclick=function(){a.register()};this.whenUnregs.push(b);var d=document.createElement("button");d.setAttribute("type","button");d.appendChild(document.createTextNode("Unregister"));d.onclick=function(){a.unregister()};this.whenRegs.push(d);var c=document.createElement("span");this.regTextNodes.push(c);var e=document.createDocumentFragment();
e.appendChild(b);e.appendChild(document.createTextNode(" "));e.appendChild(d);b=document.createElement("span");b.innerHTML=" <strong>Registered: </strong>";e.appendChild(b);e.appendChild(c);this.update();return e};g.prototype.update=function(){var a,b=(a=!!this.connection)?this.whenRegs:this.whenUnregs,d=a?this.whenUnregs:this.whenRegs;for(a=0;a<b.length;a++)b[a].removeAttribute("disabled");for(a=0;a<d.length;a++)d[a].setAttribute("disabled","disabled");y(this,"No")};g.prototype.runWithConnection=
function(a,b){var d=this,c=function(b){d.setConnection(b);a(b)},e=function(a){d.setConnection(void 0);b(a)};this.connection?this.connection.getRegisteredClients([],function(){a(d.connection)},function(){w(this.name,c,e)}):w(this.name,c,e)};g.prototype.onHubAvailability=function(a,b){samp.ping(a);return setInterval(function(){samp.ping(a)},b)};var w=function(a,b,d){var c=new q,e=new n("samp.webhub.register");e.addParam({"samp.name":a});e.checkParams([TYPE_MAP]);c.execute(e,function(a){var c;try{c=
new r(a,1E3)}catch(e){d(e);return}b(c)},d)},l={};l.XmlRpcRequest=n;l.XmlRpcClient=q;l.Message=function(a,b){this["samp.mtype"]=a;this["samp.params"]=b};l.TYPE_STRING=TYPE_STRING;l.TYPE_LIST=TYPE_LIST;l.TYPE_MAP=TYPE_MAP;l.register=w;l.ping=function(a){var b=new q,d=new n("samp.webhub.ping");b.execute(d,function(){a(!0)},function(){a(!1)})};l.isSubscribed=function(a,b){for(var d in a){var c;a:if(c=b,d==c||"*"===d)c=!0;else{var e=void 0;if(e=/^(.*)\.\*$/.exec(d))if(e=e[1],e===c.substring(0,e.length)){c=
!0;break a}c=!1}if(c)return!0}return!1};l.Connector=g;l.CallableClient=m;l.ClientTracker=p;return l}();
