# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DbQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Not started', max_length=15)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(default=None)),
                ('used_filters', models.IntegerField()),
                ('connectors', models.ManyToManyField(related_name='_dbquery_connectors_+', to='interface.DbQuery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StarsFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Not started', max_length=15)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(default=None)),
                ('deciders', models.ManyToManyField(related_name='_starsfilter_deciders_+', to='interface.StarsFilter')),
                ('descriptors', models.ManyToManyField(related_name='_starsfilter_descriptors_+', to='interface.StarsFilter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
