# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starsfilter',
            name='deciders',
        ),
        migrations.RemoveField(
            model_name='starsfilter',
            name='descriptors',
        ),
    ]
