# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20170313_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsfilter',
            name='deciders',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='starsfilter',
            name='descriptors',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='dbquery',
            name='connectors',
        ),
        migrations.AddField(
            model_name='dbquery',
            name='connectors',
            field=models.TextField(default=''),
        ),
    ]
