# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20170313_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbquery',
            name='queries',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
