# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_dbquery_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbquery',
            name='finish_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dbquery',
            name='queries',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dbquery',
            name='used_filters',
            field=models.IntegerField(default=''),
        ),
    ]
