# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20170315_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbquery',
            name='used_filters',
            field=models.TextField(default=''),
        ),
    ]
