# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-05 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20170315_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbquery',
            name='used_filters',
            field=models.TextField(default='---'),
        ),
    ]
